### ISSUE TITLE
nuc980 SD/TF Card Operation

### ISSUE THREAD

**Issue by zouzengming** [OpenNuvoton/MA35D1_Buildroot#3]
Hello: 
     Currently I am testing the file system of the TF card on Linux510 of NUC980DK61YC.
     using the nuvoton_nuc980_eth2uart_defconfig configuration, according to this configuration there is no TF card detected, there is no device such as mmc in the dev directory.
    Menuconfig open the NUC980_FMI_SD0 ,prompt waring "MMC[=y]&&MACH_NUC980&&NUC980_FMI_SD0[=y]|| MMC[=y] && MACH_NUC980 &&NUC980_FMI_SD0[=y]”,and make is show error.
    what configuration do I need to change to operate TF card correctly. TF card wiring: PC5-PC10, PC12, NUC980_NuWrite 1.18 can detect and read and write TF card.
     I,am  not confirm if it works on linux 4.4.
    Thanks.

**Comment by zouzengming** [comment]
make nuvoton_nuc980_defconfig ,make.
then will show the same issue.

**Comment by schung1218** [comment]
Hello @zouzengming,
The latest version fixes this issue.

**Comment by RSTurgay** [comment]
> Hello @zouzengming, The latest version fixes this issue.

Hello, I update repo and get same error. What should I do ?

**Comment by ychuang3** [comment]
Hi,

First, please take a look at the board name of your board.
I just made a test on this issue.
I am using "NK-980IOT V1.0" board, and selecting the corresponding defconfig.
And, just made a clean-build like this:

# make nuvoton_nuc980_iot_defconfig
# make linux-dirclean (if you have a pre-build)
# make

It should eventually compile successfully. If you encounter compilation errors during this process, we need to take a look at your compilation environment. It is recommended to compile in a Docker environment.

After the compilation is complete, use NuWriter to load the 'Image' and 'nuc980-iot-v1.0.dtb' into DRAM for execution. On my IoT board, the micro SD card works properly.

Best regards,
Jacky
